server:
  port: 8443  # 8443-al probaltuk 
  ssl: 
    key-store: keystore.p12 
    key-store-password: Password111 
    key-store-type: PKCS12 
    key-alias: machine_manager 

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/machine
    username: machine
    password: Password111
    driver-class-name: org.postgresql.Driver
    platform: postgres

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: validate
#    properties:
#      hibernate:
#        temp:
##           Meant to hide "Disabling contextual LOB creation as createClob() method threw error" 
##           more details: http://vkuzel.blogspot.hu/2016/03/spring-boot-jpa-hibernate-atomikos.html
#          use_jdbc_metadata_defaults: false
          

    
#logging:
#  level:
#    org.springframework.security: DEBUG


#logging:
#  level:
#    org.hibernate: DEBUG

#logging:
#   level: 
      # Hides HHH000424: Disabling contextual LOB creation as createClob() method threw error 
#      org.hibernate.engine.jdbc.env.internal.LobCreatorBuilderImpl: WARN
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
